### PR TITLE
Added train generator

### PR DESCRIPTION
**Pull request by KChald**
Added a train generator. Also, a way to convert expressions to tokens in order to include poly parameters in the tokenization procedure, and a way to convert tokens to expressions. The image generated is the graph and the file name of each graph can be used as token inputs for training.

### CODE REVIEW

**Comment by stasinos** [comment]
Please change the request to merging into branch autodiff-exercise instead of master

**Comment by KChald** [comment]
Changed the base branch.

**Comment by stasinos** [comment]
Correct me if I misunderstood s'thing, but I think that these are all one-liners, ie, compositions.

(a) The generation should be a bit more informed, so that it does not compose ln(exp()) or exp(ln()), which would have no effect and would be misleading to the learner.

(b) Will you cover multi-line programs, or will it be left for future work? (It is fine to focus on one-liners, but please make it explicit)

**Comment by KChald** [comment]
"These are all one-liners".
Correct. Will try to finish both a and b as soon as possibe.

**Comment by stasinos** [comment]
If you only treat one-liners, nothing else for you to do for (b). I will update the project description accordingly

**Comment by KChald** [comment]
Great. I will only fix (a) then.

**Comment by stasinos** [comment]
See commit https://github.com/stasinos/machine_learning/commit/7e3136c72ac30713832c5348bcf3d77f0c4f2700 about (b)

**Comment by KChald** [comment]
Made minor fixes + exception handling. ( (a) is handled )

**Comment by KChald** [comment]
pic = Image.open("{}.png".format(title)).convert('1') 
     pic.save( "{}-bw.png".format(title) )
     plt.close(fig) # <-

The last line should be added in write_figure because it opens an empty diagram after every execution resulting in warning when write_figure is inside a loop with more than 20 iterations.

**Comment by stasinos** [comment]
You can keep on adding commits to the pull request.

**Comment by KChald** [comment]
Thank you! I see no other changes in the code. Any other suggestions would be welcomed. If everything is ok I will continue with the merge.

**Comment by stasinos** [comment]
Sure, go ahead. I recommend a squash merge, since this branch only has contributions from you and during a relatively short period, so no need to clutter the project history. Merge into autodiff-exercise and then delete this branch.

**Review by stasinos — APPROVED** [review]
Looks good to merge

**Comment by KChald** [comment]
Done

**Pull request merged**
